# Nick Wan Data Science Bootcamp Day 2

The second day of notes for the Nick Wan data science bootcamp

## Read in the Data and Initialize Packages

In [1]:
import pandas as pd

df = pd.read_csv('data/2023-nwbc-reds.csv')
df.head()

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,pitcher_name,batter,pitcher,events,description,...,delta_home_win_exp,delta_run_exp,attack_zone,swing,batter_name,total_score,is_strike,is_2_strikes,is_high_velo,strike_in_heart
0,FF,2022-10-05,93.8,2.39,5.44,"Hughes, Brandon",605244,676714,field_out,hit_into_play,...,0.0,-0.083,heart,0,"garcia, aramis",17,0,1,0,0
1,FF,2022-10-05,93.3,2.30,5.51,"Hughes, Brandon",605244,676714,NaN,ball,...,0.0,0.014,shadow,0,"garcia, aramis",17,0,1,0,0
2,SL,2022-10-05,84.3,2.45,5.21,"Hughes, Brandon",605244,676714,NaN,ball,...,0.0,0.011,waste,0,"garcia, aramis",17,0,1,0,0
3,FF,2022-10-05,93.8,2.32,5.48,"Hughes, Brandon",605244,676714,NaN,called_strike,...,0.0,-0.023,heart,0,"garcia, aramis",17,1,0,0,1
4,FF,2022-10-05,94.1,2.34,5.54,"Hughes, Brandon",605244,676714,NaN,swinging_strike,...,0.0,-0.017,heart,0,"garcia, aramis",17,1,0,1,1

## And and Or Statements in Python

* To check if two conditions are true, use an AND statement with the `&` symbol
* To check if either of two conditions are true, use an OR statement with the `|` symbol

* Find the rows where the home team is CIN and it is the top of the inning

In [2]:
df.loc[(df['home_team']=='CIN') & (df['inning_topbot']=='Top')].head()

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,pitcher_name,batter,pitcher,events,description,...,delta_home_win_exp,delta_run_exp,attack_zone,swing,batter_name,total_score,is_strike,is_2_strikes,is_high_velo,strike_in_heart
13,FF,2022-10-05,95.5,-2.74,6.08,"Strickland, Hunter",621550,519326,field_out,hit_into_play,...,0.0,-0.099,heart,0,"wisdom, patrick",17,0,0,1,0
14,FF,2022-10-05,94.2,-2.82,6.05,"Strickland, Hunter",663845,519326,strikeout,called_strike,...,0.0,-0.134,heart,0,"rivas, alfonso",17,1,1,1,1
15,FF,2022-10-05,94.3,-3.04,5.84,"Strickland, Hunter",663845,519326,NaN,ball,...,0.0,0.023,waste,0,"rivas, alfonso",17,0,1,1,0
16,FC,2022-10-05,88.1,-3.07,5.74,"Strickland, Hunter",663845,519326,NaN,foul,...,0.0,-0.036,shadow,0,"rivas, alfonso",17,1,0,0,0
17,FF,2022-10-05,95.3,-3.00,5.86,"Strickland, Hunter",663845,519326,NaN,ball,...,0.0,0.016,chase,0,"rivas, alfonso",17,0,0,1,0

* Create a new column called `is_reds_pitcher` where the home team is CIN and it is the top of the inning OR the away team is CIN and it is the bottom of the inning

In [3]:
df['is_reds_pitcher'] = 0
df.loc[((df['home_team']=='CIN') & (df['inning_topbot']=='Top')) | (df['away_team']=='CIN') & (df['inning_topbot']=='Bot'), 'is_reds_pitcher'] = 1
df.head()

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,pitcher_name,batter,pitcher,events,description,...,delta_run_exp,attack_zone,swing,batter_name,total_score,is_strike,is_2_strikes,is_high_velo,strike_in_heart,is_reds_pitcher
0,FF,2022-10-05,93.8,2.39,5.44,"Hughes, Brandon",605244,676714,field_out,hit_into_play,...,-0.083,heart,0,"garcia, aramis",17,0,1,0,0,0
1,FF,2022-10-05,93.3,2.30,5.51,"Hughes, Brandon",605244,676714,NaN,ball,...,0.014,shadow,0,"garcia, aramis",17,0,1,0,0,0
2,SL,2022-10-05,84.3,2.45,5.21,"Hughes, Brandon",605244,676714,NaN,ball,...,0.011,waste,0,"garcia, aramis",17,0,1,0,0,0
3,FF,2022-10-05,93.8,2.32,5.48,"Hughes, Brandon",605244,676714,NaN,called_strike,...,-0.023,heart,0,"garcia, aramis",17,1,0,0,1,0
4,FF,2022-10-05,94.1,2.34,5.54,"Hughes, Brandon",605244,676714,NaN,swinging_strike,...,-0.017,heart,0,"garcia, aramis",17,1,0,1,1,0

## Some Nice Python Shorthand

* If you want to get everything (either all rows or all columns), then use `:`
* If you want to get specific columns, put the column names into a list

EX: Get all the rows from your dataframe with only the pitcher name, pitch name, and whether the pitch was a strike columns

In [4]:
df.loc[:, ['pitcher_name', 'pitch_name', 'is_strike']].head()

      pitcher_name       pitch_name  is_strike
0  Hughes, Brandon  4-Seam Fastball          0
1  Hughes, Brandon  4-Seam Fastball          0
2  Hughes, Brandon           Slider          0
3  Hughes, Brandon  4-Seam Fastball          1
4  Hughes, Brandon  4-Seam Fastball          1

## Pivot Tables in Python

* We can create pivot tables from our pandas DataFrames using the `groupby()` function
* The result of this is NOT a dataframe... so if you want some aggragation functions just tack them on to the end with normal function notation

In [5]:
df.loc[df['is_reds_pitcher']==1, ['pitcher_name', 'pitch_name', 'is_strike']].groupby(['pitcher_name', 'pitch_name'], as_index=False).mean()

        pitcher_name       pitch_name  is_strike
0    Anderson, Chase  4-Seam Fastball   0.437500
1    Anderson, Chase         Changeup   0.542857
2    Anderson, Chase        Curveball   0.368421
3    Anderson, Chase           Cutter   0.438202
4    Anderson, Chase           Sinker   0.464286
..               ...              ...        ...
141      Zeuch, T.J.           Slider   0.373134
142     Zimmer, Kyle  4-Seam Fastball   0.400000
143     Zimmer, Kyle         Changeup   1.000000
144     Zimmer, Kyle        Curveball   1.000000
145     Zimmer, Kyle           Slider   1.000000

[146 rows x 3 columns]

In [6]:
# write our work to a csv so we can use it later
df.to_csv('./data/2023-nwbc-reds.csv', index=False)